// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"RingMenu","status":true,"description":"Pivert ring menu","parameters":{"Images directory":"img/ringMenu","Hover image":"hover","Use Keyboard":"false"}}
];
